Update 36-split-me-and-new-jwt.sql
TFNS/CTFNote pull request #124
Opened 2021-12-07 13:34 UTC by ISnackable

Fix migration error: could not find a function named "me".
I had the above error when running this sql file on a cloud database, hopefully this commit fixes it.

2021-12-07 18:06 UTC, JJ-8 reviewed
Thank you for raising _and_ fixing an issue! :)

Changing old migrations however is not possible as far as I know since the checksum will mismatch when someone updates CTFNote.

Did you update from an older CTFNote installation? Or do you have a fresh install of CTFNote?

2021-12-07 18:20 UTC, ISnackable commented
Oh I see... to answer your question, I had a fresh install of CTFNote.

2021-12-09 14:54 UTC, XeR requested changes
JJ-8 is right. We *cannot* change a mutation after it has been applied.
The only time we are "allowed" to change a mutation is when it's so broken that it could not be applied.
... which is the exact situation you're in right now.

This error should not happen. I could not reproduce the issue.
I've upgraded and installed new CTFNote instances since that migration without any issues.
Can you tell us more about your environment ? There has to be something different.

2021-12-09 15:16 UTC, ISnackable commented
Hi, you may close the PR, did not realized that a mutation cannot be changed after it has been applied. 

I was deploying the migration on Yugabyte DB, a cloud database. I believe this issue occurred as the `search_path` in my environment did not contain the schema `ctfnote`, hence it was not able to find the function `me` without specifying the schema.

2021-12-09 17:23 UTC, JJ-8 commented
Closing as requested

2021-12-09 17:23 UTC, closed without merging