Basic contribution guide
TFNS/CTFNote pull request #130
Opened 2021-12-20 09:29 UTC by SakiiR

This is open to review/change

2021-12-20 13:22 UTC, SakiiR commented
We can also add this as a wiki page. For now, and for review purpose, it's a new file

2021-12-21 12:16 UTC, JJ-8 requested changes
You mention that you have to fork it after the installation steps. I think this should be before the installation so you don't have to mess with the git settings to change the repo.

2021-12-21 13:06 UTC, SakiiR commented
I moved the "git process" part on top of the document

2021-12-21 16:51 UTC, JJ-8 approved these changes
Yes, this is much better! :)

It is a quite basic guide, but I don't know what to add more. It seems you have covered all the steps already!

@B-i-t-K or @XeR, do you have any additions?

2021-12-21 16:53 UTC, SakiiR commented
Thanks !

I think in the future, we could add some instruction on:

- Add a new migration
- Flushing the database
- Add a new page/component to the front app
- Implement a new query/migration

And other specific things about the technologies we use.

2021-12-21 17:01 UTC, JJ-8 commented
Ah, yes, these are very good additions. But do we want to include them now? Or should this PR just be the basics and we can extend it later?

2021-12-22 10:16 UTC, SakiiR commented
> Ah, yes, these are very good additions. But do we want to include them now? Or should this PR just be the basics and we can extend it later?

Maybe later yes =)

2021-12-22 14:49 UTC, XeR requested changes
Minor details about "moderators" and header depth.


Regarding the 2-man review requirements : does the PR submitter count as one if they are an established contributor ?
e.g. if BitK or JJ-8 makes a PR, does it start at 1/2 ?
I'm thinking about the few times where BitK and I did pair programming : he would push stuff, I would test it and approve it to get bugs fixed faster.

2021-12-22 14:49 UTC, XeR commented on CONTRIBUTING.md
> +When contributing to this repository, please first discuss the change you wish to make via issue with the owners/moderators of this repository before making a change.
What's a moderator?
I think we should use the more generic term "contributors" or "collaborators". The later is what Github uses.

2021-12-22 14:49 UTC, XeR commented on CONTRIBUTING.md
> +You can also create the pull request before finishing the job but don't forget to add "WiP: " as a suffix in the title to let the moderators know you are still working on the request.
cf. previous comment regarding "moderators"

2021-12-22 14:49 UTC, XeR commented on CONTRIBUTING.md
> +### Review
Should be a level 2 header

2021-12-22 19:34 UTC, JJ-8 commented
> Regarding the 2-man review requirements : does the PR submitter count as one if they are an established contributor ?

Actually, it is a 1-man review requirement, right? For example, I have just approved #131 and now I can click to merge it. So only one reviewer is required (where the author does not count as a reviewer). However, I never click 'merge PR' since I think it is better if someone else also looks at the PR (like this PR).

2021-12-22 19:38 UTC, JJ-8 commented
Maybe something else that is good to add at some point: where should a PR point to by default? The dev branch or the main branch?

2021-12-22 19:42 UTC, JJ-8 commented
Oh, and one more thing: maybe mentioning somewhere that migrations can not be changed after commitment (like [this](https://github.com/TFNS/CTFNote/pull/124#pullrequestreview-827792374) situation).

2021-12-22 21:32 UTC, XeR commented
> Actually, it is a 1-man review requirement, right?

Yes. It's currently configured at 1 reviewer for main and dev. Administrators can force merge on dev only.


> where should a PR point to by default?

This is addressed in the "Git process" part :

>  Once you think the job is done, issue the pull request and target the **dev** branch of the official CTFNote repository.


> maybe mentioning somewhere that migrations can not be changed after commitment 

Good idea !

2022-01-30 23:28 UTC, XeR approved these changes

2022-01-30 23:28 UTC, XeR commented
Merged manually in 0a17f424e282f48de0a18a80a7affbb4231dab14

2022-01-30 23:28 UTC, closed without merging