[WIP] Add Discord integration checks to frontend.
TFNS/CTFNote pull request #296
Opened 2024-07-17 08:25 UTC by daanbreur

Implementation of issue #292.

Adds a warning telling you the integration has been disabled

![image](https://github.com/user-attachments/assets/f4b5e361-9ea2-4a90-927f-57faf5ec748d)

![image](https://github.com/user-attachments/assets/f155e01f-e8c4-4780-ba8c-eecf8b4cc105)

2024-07-17 08:49 UTC, JJ-8 requested changes
I have some small comments, see the review.

2024-07-17 08:49 UTC, JJ-8 commented on front/src/pages/Settings.vue
> +              v-if="settings.discordIntegrationEnabled"
This can be a `v-else` right?

2024-07-17 08:49 UTC, JJ-8 commented on front/src/components/CTF/Guests.vue
> +    <div v-if="settings.discordIntegrationEnabled" class="row q-mt-sm">
This can be a `v-else` right?

2024-07-17 08:49 UTC, JJ-8 commented on api/migrations/54-add-discord-integration-enabled.sql
> +GRANT UPDATE ("discord_integration_enabled") ON ctfnote.settings TO user_postgraphile;
This dit you remove the update rights for `user_admin`? Does this still work with changing the iCal password through the admin settings? Or is this only this single column which can only be changed by the API and not even by the admin?

2024-07-17 08:49 UTC, JJ-8 commented on api/src/index.ts
> +  const pgClient = await connectToDatabase(); //? maybe we should not keep this dependency in the discord folder?
I want to do a cleanup of the Discord integration when I start working on https://github.com/TFNS/CTFNote/issues/239 and then I will reorganize this too.

2024-07-17 08:49 UTC, JJ-8 commented on front/src/pages/Settings.vue
> +                The Discord integration is currently disabled on the backend.
`disabled on the backend.` -> `disabled in the backend.` or just `disabled.`

2024-07-17 08:49 UTC, JJ-8 commented on front/src/components/CTF/Guests.vue
> +        The Discord integration is currently disabled on the backend.
`disabled on the backend.` -> `disabled in the backend.` or just `disabled.`

2024-07-17 08:50 UTC, JJ-8 commented
The build also fails due to the GraphQL schema file not being up to date. I can give it an attempt too of creating this file since you already mentioned on Discord that you had issues with this. Something is going wrong at least.

2024-07-17 08:56 UTC, daanbreur commented
> The build also fails due to the GraphQL schema file not being up to date. I can give it an attempt too of creating this file since you already mentioned on Discord that you had issues with this. Something is going wrong at least.

That would be great, we are using all the correct versions so idk whats going on. 🤷

2024-07-17 11:05 UTC, daanbreur commented
Seems like running it under a linux virtualmachine fixed the codegen issue, i have no clue what the caused the bug itself tho.

2024-07-17 16:19 UTC, daanbreur commented
![image](https://github.com/user-attachments/assets/5da46ebb-9a56-45ae-acfb-8e06f6951bbe)

![image](https://github.com/user-attachments/assets/393532e5-b3a0-405b-a99d-983dca247ee0)

Fixed user_admin permissions in the latest commit by revoking their table wide update then granting them the columns seperately

2024-07-18 14:44 UTC, JJ-8 approved these changes
Tested it and works as expected. Code looks good to me. Thank you for your contribution!

2024-07-18 14:44 UTC, merged

2024-07-18 14:53 UTC, daanbreur commented
Your welcome. Just now I did notice the generated GraphQL model is still a bit off.